var express = require('express')
var controller = require('../controllers/server.controller')
var router = express.Router()

router.get('/', controller.showMainPage)
router.get('/analytic', controller.showAnalyticPage)
router.get('/analytic/getExNumArticle', controller.getExNumArticle)
router.get('/analytic/getExRegArticle', controller.getExRegArticle)
router.get('/analytic/getExHisArticle', controller.getExHisArticle)
router.get('/analytic/getRevsByUsertypeByYear', controller.getRevsByUsertypeByYear)
router.get('/analytic/getRevDisByUsertype', controller.getRevDisByUsertype)
router.get('/analytic/getTotalRevAllTitle', controller.getTotalRevAllTitle)
router.get('/analytic/getTotalRevTitle', controller.getTotalRevTitle)
router.get('/analytic/getTopRegularUsers', controller.getTopRegularUsers)
router.get('/analytic/getRevDisByYearByUsertypeArticle', controller.getRevDisByYearByUsertypeArticle)
router.get('/analytic/getRevDisByUsertypeArticle', controller.getRevDisByUsertypeArticle)
router.get('/analytic/getRevDisByYearTopRegUser', controller.getRevDisByYearTopRegUser)
router.get('/analytic/getArtRevByUser', controller.getArtRevByUser)
router.get('/analytic/getAutoComplete', controller.getAutoComplete)
router.get('/analytic/getRevTimeByUser', controller.getRevTimeByUser)
router.get('/analytic/getLastTimeTitle', controller.getLastTimeTitle)
router.get('/analytic/updateDB', controller.updateDB)
router.get('/analytic/updateUserType', controller.updateUserType)
router.get('/analytic/redditPull', controller.redditPull)
router.post('/signup', controller.signup)
router.post('/login', controller.login)
router.post('/resetPassword', controller.resetPassword)
router.get('/logout', controller.logout)

module.exports = router